export const projects = [
  {
    id: 1,
    title: "Onde Social",
    category: "Rede Social",
    description:
      "Plataforma de rastreamento e compartilhamento de localização em tempo real.",
    image: "/portfolio/onde.png",
    tech: ["Next.js", "WebSockets", "Maps API"],
    link: "https://onde.social",
    featured: true,
    color: "from-amber-500 to-orange-500",
  },
  {
    id: 2,
    title: "Vitae.cv",
    category: "Produtividade",
    description:
      "Plataforma inteligente para criação e gestão de currículos profissionais.",
    image: "/portfolio/vitae.png",
    tech: ["React", "TypeScript", "AI Integration"],
    link: "https://vitae.cv",
    featured: true,
    color: "from-orange-600 to-red-500",
  },
  {
    id: 3,
    title: "PGV - Sistema de Gestão",
    category: "Enterprise",
    description:
      "Sistema completo de gestão veicular com controle de acesso e auditoria.",
    image: "/portfolio/pgv-sistema.jpg",
    tech: ["Go", "React", "PostgreSQL", "Docker"],
    github: "https://github.com/sudotech/pgv",
    featured: false,
    color: "from-red-500 to-orange-600",
  },
  {
    id: 4,
    title: "Velooh",
    category: "Mobilidade",
    description:
      "Plataforma de compartilhamento e aluguel de bicicletas urbanas.",
    image: "/portfolio/velooh.png",
    tech: ["Next.js", "Node.js", "PostgreSQL"],
    link: "https://velooh.com",
    featured: false,
    color: "from-amber-600 to-yellow-500",
  },
  {
    id: 5,
    title: "ReCycling Bikes",
    category: "Sustentabilidade",
    description:
      "E-commerce focado em bicicletas recicladas e sustentabilidade urbana.",
    image: "/portfolio/recycling.png",
    tech: ["WordPress", "WooCommerce", "Custom Theme"],
    link: "https://www.recyclingbikes.co/",
    featured: false,
    color: "from-yellow-500 to-amber-600",
  },
  {
    id: 6,
    title: "PyNorte 2023",
    category: "Eventos",
    description:
      "Site oficial do maior evento Python da região Norte do Brasil.",
    image: "/portfolio/pynorte.png",
    tech: ["Python", "Django", "PostgreSQL"],
    link: "https://2023.pythonnorte.org/",
    featured: false,
    color: "from-orange-500 to-red-600",
  },
  {
    id: 7,
    title: "Inovatech",
    category: "Tecnologia",
    description: "Plataforma de inovação tecnológica e gestão de projetos.",
    image: "/portfolio/inovatech.png",
    tech: ["Next.js", "TypeScript", "Tailwind CSS"],
    link: "https://inovatec.junowoz.com",
    featured: false,
    color: "from-red-600 to-orange-500",
  },
];
