export const projects = [
  {
    id: 1,
    title: "Onde",
    category: "Rede Social e ERP",
    description:
      "Plataforma de gerenciamento e fidelidade para estabelecimentos.",
    image: "/portfolio/onde.png",
    tech: ["Web", "PWA", "Mobile"],
    link: "https://portal.onde.social",
    featured: false,
    color: "from-amber-500 to-orange-500",
  },
  {
    id: 2,
    title: "Vitae.cv",
    category: "Produtividade",
    description:
      "Plataforma inteligente para criação e gestão de currículos profissionais.",
    image: "/portfolio/vitae.png",
    tech: ["Web", "PWA", "AI Integration"],
    link: "https://vitae.cv",
    featured: false,
    color: "from-orange-600 to-red-500",
  },
  {
    id: 3,
    title: "PGV - Sistema de Gestão Veicular",
    category: "Governo",
    description:
      "Sistema completo de gestão veicular com controle de acesso e auditoria para a Polícia Civil.",
    image: "/portfolio/pgv-sistema.jpg",
    tech: ["Web", "Plataforma"],
    link: "https://pgv.sudotech.com.br",
    featured: false,
    color: "from-red-500 to-orange-600",
  },
  {
    id: 4,
    title: "AMZ Geradores",
    category: "Energia",
    description: "Site institucional da AMZ Geradores.",
    image: "/portfolio/amz-geradores.png",
    tech: ["Web"],
    link: "https://amzgeradores.com.br",
    featured: false,
    color: "from-red-500 to-orange-600",
  },
  // {
  //   id: 4,
  //   title: "SIMOF - Sistema de Monitoramento de Frotas",
  //   category: "Governo",
  //   description:
  //     "Plataforma para rastrear o desempenho dos motoristas da Transpetro.",
  //   image: "/portfolio/simof.png",
  //   tech: ["Web", "PWA", "Mobile"],
  //   link: "https://simof.sudotech.com.br",
  //   featured: false,
  //   color: "from-red-500 to-orange-600",
  // },
  // {
  //   id: 5,
  //   title: "GerontoChat",
  //   category: "Saúde",
  //   description: "Chatbot assistente para profissionais de saúde da FUNATI.",
  //   image: "/portfolio/gerontochat.png",
  //   tech: ["Web", "PWA", "Mobile"],
  //   link: "https://gerontochat.com",
  //   featured: false,
  //   color: "from-red-500 to-orange-600",
  // },
  // {
  //   id: 6,
  //   title: "NexGás",
  //   category: "Energia",
  //   description:
  //     "Plataforma para a NexGás, uma distribuidora de Gás Amazonense.",
  //   image: "/portfolio/nexgas.png",
  //   tech: ["Web", "PWA", "Mobile"],
  //   link: "https://nexgas.com",
  //   featured: false,
  //   color: "from-red-500 to-orange-600",
  // },
  {
    id: 5,
    title: "Velooh",
    category: "Mobilidade",
    description: "Plataforma de anúncios para tablets em viagens de Uber.",
    image: "/portfolio/velooh.png",
    tech: ["Web", "PWA", "Mobile"],
    link: "https://velooh.com",
    featured: false,
    color: "from-amber-600 to-yellow-500",
  },
  {
    id: 6,
    title: "Inovatech",
    category: "Educação",
    description:
      "Plataforma para o evento de inovação tecnológica do Grupo Fametro.",
    image: "/portfolio/inovatech.png",
    tech: ["Web", "PWA", "Mobile"],
    link: "https://inovatec.junowoz.com",
    featured: false,
    color: "from-red-600 to-orange-500",
  },
];
