export const projects = [
  {
    id: 1,
    title: "Onde",
    category: "Rede Social e ERP",
    description:
      "Plataforma de gerenciamento e fidelidade para estabelecimentos.",
    image: "/portfolio/onde.png",
    tech: ["Web", "PWA", "Mobile"],
    link: "https://portal.onde.social",
    featured: false,
    color: "from-amber-500 to-primary",
  },
  {
    id: 2,
    title: "PGV - Sistema de Gestão Veicular",
    category: "Governo",
    description:
      "Sistema completo de gestão veicular com controle de acesso e auditoria para a Polícia Civil.",
    image: "/portfolio/pgv-sistema.jpg",
    tech: ["Web", "Plataforma ERP"],
    link: "https://pgv.sudotech.com.br",
    featured: false,
    color: "from-amber-500 to-primary",
  },
  {
    id: 3,
    title: "Plataforma de Saúde Digital (FUnATI)",
    category: "Saúde Digital",
    description:
      "Consultoria para gestão e evolução do Prontuário Eletrônico da Pessoa Idosa (PEP), garantindo interoperabilidade, segurança (LGPD) e suporte técnico.",
    image: "/portfolio/funati-pep.jpg",
    tech: ["Gestão de Produtos", "Saúde", "GovTech", "LGPD"],
    link: null,
    featured: true,
    color: "from-amber-500 to-primary",
  },
  {
    id: 4,
    title: "GerontoCare",
    category: "Health Tech",
    description:
      "Coleta de dados de saúde com ingestão segura em nuvem e visualização para monitoramento de idosos.",
    image: "/portfolio/funati.png",
    tech: ["Android", "Google Cloud", "BigQuery", "IA", "Wearables", "FastAPI"],
    link: null,
    featured: true,
    color: "from-amber-500 to-primary",
  },
  {
    id: 5,
    title: "AMZ Geradores",
    category: "Energia",
    description: "Site CMS da AMZ Geradores.",
    image: "/portfolio/amz-geradores.png",
    tech: ["Web", "CMS"],
    link: "https://amzgeradores.com.br",
    featured: false,
    color: "from-amber-500 to-primary",
  },
  // {
  //   id: 4,
  //   title: "SIMOF - Sistema de Monitoramento de Frotas",
  //   category: "Governo",
  //   description:
  //     "Plataforma para rastrear o desempenho dos motoristas da Transpetro.",
  //   image: "/portfolio/simof.png",
  //   tech: ["Web", "PWA", "Mobile"],
  //   link: "https://simof.sudotech.com.br",
  //   featured: false,
  //color: "from-amber-500 to-primary",  // },
  // {
  //   id: 5,
  //   title: "GerontoChat",
  //   category: "Saúde",
  //   description: "Chatbot assistente para profissionais de saúde da FUNATI.",
  //   image: "/portfolio/gerontochat.png",
  //   tech: ["Web", "PWA", "Mobile"],
  //   link: "https://gerontochat.com",
  //   featured: false,
  //color: "from-amber-500 to-primary",  // },
  // {
  //   id: 6,
  //   title: "NexGás",
  //   category: "Energia",
  //   description:
  //     "Plataforma para a NexGás, uma distribuidora de Gás Amazonense.",
  //   image: "/portfolio/nexgas.png",
  //   tech: ["Web", "PWA", "Mobile"],
  //   link: "https://nexgas.com",
  //   featured: false,
  //color: "from-amber-500 to-primary",  // },
  {
    id: 6,
    title: "Velooh",
    category: "Mobilidade",
    description: "Plataforma de anúncios para tablets em viagens de Uber.",
    image: "/portfolio/velooh.png",
    tech: ["Web", "PWA", "Mobile"],
    link: "https://velooh.com",
    featured: false,
    color: "from-amber-500 to-primary",
  },
];
